### ISSUE TITLE
Issues encountered while using the FulfillmentInbound V2024-03-20 version.

### ISSUE THREAD

**Issue by TSLdob** [saleweaver/python-amazon-sp-api#1393]
Seeking help... How can I solve these two problems when using FulfillmentInbound V2024-03-20?

When I use FulfillmentInbound.get_shipment, I can't get all the return values, such as shipmentConfirmationId. The official documentation indicates that this return value is optional, but I don't know how to select it.

When I use some methods, I get an error, such as with FulfillmentInbound.update_shipment_delivery_window, which returns [{'code': 'Unauthorized', 'message': 'Access to requested resource is denied.', 'details': ''}].

**Comment by saleweaver** [comment]
This seems to be related to an open pull request. Please make sure that the endpoint you're calling actually exists for the version you're using. There's a PR on the way to mark incorrect method usage for versioned endpoints.

**Comment by xEverth** [comment]
Hello!

Just a few preliminary information that may help:

Carefully look at the path for the request: for the /v0/ it was /fba/inbound, for the /2024-03-20/ it is /inbound/fba. This mostly explains the "Access to requested resource is denied"

Some operations have been discontinued from the /v0/ to the /2024-03-20/ and the notice on SP-API docs says the following:
Warning!


> All operations other than getLabels, getBillOfLading, and getPrepInstructions are deprecated and will be removed on December 20, 2024.
> 
> For continued programmatic access to Fulfillment Inbound, migrate to the [Fulfillment Inbound v2024-03-20 API](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference).

Now some questions for @saleweaver : 
- Is the test suite meant to run against the SANDBOX endpoints? I'm having issues with authentication only on tests
- The test suite itself has calls to the discontinued shipments endpoints, I may want to edit or add a few discontinuation-related tests
- Since the path changes from inboundFba /v0/ to /2024-03-20/ should we still use the same class and have the sp_endpoint decorator adjust the path, make different methods or separate the class?
- Can I reach out to you on Slack for questions like the above?
Thanks
